### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by surajrimal07** [sthsuyash/News-algorithm#1]
Thank you for open sourcing this awesome project. Dherai kura sikne mauka paye. But kai files haru missing rahexa hajur ko repo ma like files from /dataset, models/sentiment_transformer.pkl etc. Is it possible to provide these files too? Thank you.

**Comment by sthsuyash** [comment]
@surajrimal07  This project is currently under development, so I would be uploading the files after completion. Also large files could cause some issues so I may upload the links to dataset and the pickle files. Stay tuned
